local Plug = vim.fn["plug#"]

vim.call("plug#begin")
    Plug("tpope/vim-fugitive")
    Plug("folke/which-key.nvim")
    Plug("EdenEast/nightfox.nvim")
    Plug("williamboman/mason.nvim")
    Plug("williamboman/mason-lspconfig.nvim")
    Plug("junegunn/fzf.vim")
    Plug("nvim-treesitter/nvim-treesitter", {["do"] = ":TSUpdate"})
    Plug("ludovicchabant/vim-gutentags")
    Plug("neovim/nvim-lspconfig")
    Plug("j-hui/fidget.nvim", { ["tag"] = "legacy" })
    Plug("hrsh7th/nvim-cmp")
    Plug("hrsh7th/cmp-nvim-lsp")
    Plug("hrsh7th/cmp-buffer")
    Plug("hrsh7th/cmp-nvim-lua")
    Plug("hrsh7th/cmp-path")
    Plug("hrsh7th/cmp-cmdline")
    Plug("L3MON4D3/LuaSnip")
    Plug("vim-airline/vim-airline")
    Plug("gpanders/editorconfig.nvim")
    Plug("easymotion/vim-easymotion")
    Plug("kassio/neoterm")
    Plug("simrat39/rust-tools.nvim")
    Plug("mfussenegger/nvim-dap")
    Plug("rcarriga/nvim-dap-ui")
    Plug("nvim-lua/plenary.nvim")
vim.call("plug#end")

